const fs = require('fs');
const path = require('path');

const podfilePath = path.join(__dirname, '..', 'ios', 'Podfile');

if (fs.existsSync(podfilePath)) {
  let content = fs.readFileSync(podfilePath, 'utf8');
  
  const patchCode = `
    installer.pods_project.targets.each do |target|
      if target.name == 'ExpoModulesJSI'
        target.build_configurations.each do |config|
          config.build_settings['SWIFT_STRICT_CONCURRENCY'] = 'off'
          config.build_settings['SWIFT_ENFORCE_EXCLUSIVE_ACCESS'] = 'OFF'
          config.build_settings['GCC_WARN_INHIBIT_ALL_WARNINGS'] = 'YES'
        end
      else
        target.build_configurations.each do |config|
          config.build_settings['SWIFT_STRICT_CONCURRENCY'] = 'minimal'
          config.build_settings['SWIFT_TREAT_WARNINGS_AS_ERRORS'] = 'NO'
          config.build_settings['GCC_WARN_INHIBIT_ALL_WARNINGS'] = 'YES'
        end
      end
    end
`;

  if (!content.includes("config.build_settings['SWIFT_STRICT_CONCURRENCY'] = 'off'")) {
    // If our older generic patch exists, replace it
    if (content.includes("config.build_settings['SWIFT_STRICT_CONCURRENCY'] = 'minimal'")) {
      content = content.replace(/installer\.pods_project\.targets\.each do \|target\|[\s\S]*?end\s*end/m, patchCode.trim());
      fs.writeFileSync(podfilePath, content, 'utf8');
      console.log('✓ Updated SWIFT_STRICT_CONCURRENCY settings in ios/Podfile for ExpoModulesJSI');
    } else if (content.includes('post_install do |installer|')) {
      content = content.replace('post_install do |installer|', 'post_install do |installer|' + patchCode);
      fs.writeFileSync(podfilePath, content, 'utf8');
      console.log('✓ Injected SWIFT_STRICT_CONCURRENCY settings into ios/Podfile');
    } else {
      content += `
post_install do |installer|
${patchCode}
end
`;
      fs.writeFileSync(podfilePath, content, 'utf8');
      console.log('✓ Appended post_install hook to ios/Podfile');
    }
  } else {
    console.log('✓ ios/Podfile already contains target-specific SWIFT_STRICT_CONCURRENCY settings');
  }
} else {
  console.log('⚠ ios/Podfile not found (will be generated by prebuild)');
}
