const fs = require('fs');
const path = require('path');

const podfilePath = path.join(__dirname, '..', 'ios', 'Podfile');

if (fs.existsSync(podfilePath)) {
  let content = fs.readFileSync(podfilePath, 'utf8');
  
  const patchCode = `
    installer.pods_project.targets.each do |target|
      if target.name == 'ExpoModulesJSI'
        target.build_configurations.each do |config|
          config.build_settings['SWIFT_STRICT_CONCURRENCY'] = 'off'
          config.build_settings['SWIFT_ENFORCE_EXCLUSIVE_ACCESS'] = 'none'
          config.build_settings['SWIFT_TREAT_WARNINGS_AS_ERRORS'] = 'NO'
          config.build_settings['GCC_WARN_INHIBIT_ALL_WARNINGS'] = 'YES'
        end
      else
        target.build_configurations.each do |config|
          config.build_settings['SWIFT_STRICT_CONCURRENCY'] = 'minimal'
          config.build_settings['SWIFT_TREAT_WARNINGS_AS_ERRORS'] = 'NO'
          config.build_settings['GCC_WARN_INHIBIT_ALL_WARNINGS'] = 'YES'
        end
      end
    end
`;

  // Always replace any existing patch block with the updated one
  if (content.includes("SWIFT_STRICT_CONCURRENCY")) {
    content = content.replace(/installer\.pods_project\.targets\.each do \|target\|[\s\S]*?end\s*end/m, patchCode.trim());
    fs.writeFileSync(podfilePath, content, 'utf8');
    console.log('✓ Updated SWIFT_STRICT_CONCURRENCY settings in ios/Podfile (SWIFT_ENFORCE_EXCLUSIVE_ACCESS=none)');
  } else if (content.includes('post_install do |installer|')) {
    content = content.replace('post_install do |installer|', 'post_install do |installer|' + patchCode);
    fs.writeFileSync(podfilePath, content, 'utf8');
    console.log('✓ Injected SWIFT_STRICT_CONCURRENCY settings into ios/Podfile');
  } else {
    content += `
post_install do |installer|
${patchCode}
end
`;
    fs.writeFileSync(podfilePath, content, 'utf8');
    console.log('✓ Appended post_install hook to ios/Podfile');
  }
} else {
  console.log('⚠ ios/Podfile not found (will be generated by prebuild)');
}
