const fs = require('fs');
const path = require('path');

const podfilePath = path.join(__dirname, '..', 'ios', 'Podfile');

if (fs.existsSync(podfilePath)) {
  let content = fs.readFileSync(podfilePath, 'utf8');
  const patchCode = `
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_STRICT_CONCURRENCY'] = 'minimal'
        config.build_settings['SWIFT_TREAT_WARNINGS_AS_ERRORS'] = 'NO'
        config.build_settings['GCC_WARN_INHIBIT_ALL_WARNINGS'] = 'YES'
      end
    end
`;
  if (!content.includes("SWIFT_STRICT_CONCURRENCY")) {
    if (content.includes('post_install do |installer|')) {
      content = content.replace('post_install do |installer|', 'post_install do |installer|' + patchCode);
      fs.writeFileSync(podfilePath, content, 'utf8');
      console.log('Successfully injected SWIFT_STRICT_CONCURRENCY=minimal into ios/Podfile');
    } else {
      // Append if no post_install exists
      content += `
post_install do |installer|
${patchCode}
end
`;
      fs.writeFileSync(podfilePath, content, 'utf8');
      console.log('Successfully appended post_install hook to ios/Podfile');
    }
  } else {
    console.log('ios/Podfile already contains SWIFT_STRICT_CONCURRENCY settings');
  }
} else {
  console.log('ios/Podfile not found (will be generated by prebuild)');
}
